steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/storymimi-backend:$COMMIT_SHA', '.']
  
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/storymimi-backend:$COMMIT_SHA']
  
  # Tag as latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/storymimi-backend:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/storymimi-backend:latest']
  
  # Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/storymimi-backend:latest']
  
  # Deploy to Cloud Run API
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'storymimi-api'
      - '--image=gcr.io/$PROJECT_ID/storymimi-backend:latest'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--min-instances=1'
      - '--max-instances=5'
      - '--set-env-vars=REDIS_URL=redis://YOUR_REDIS_IP:6379/0'
      - '--vpc-connector=storymimi-connector'
  
  # Deploy to Cloud Run Jobs (Worker)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'update'
      - 'storymimi-worker'
      - '--image=gcr.io/$PROJECT_ID/storymimi-backend:latest'
      - '--region=us-central1'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--task-timeout=3600'
      - '--max-retries=3'
      - '--set-env-vars=REDIS_URL=redis://YOUR_REDIS_IP:6379/0'
      - '--vpc-connector=storymimi-connector'
      - '--command=celery'
      - '--args=-A,app.core.celery_app:celery_app,worker,--loglevel=info'

images:
  - 'gcr.io/$PROJECT_ID/storymimi-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/storymimi-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY 